### ISSUE TITLE
Installation with latest jupyterlab release

### ISSUE THREAD

**Issue by gh43r** [timkpaine/jupyterlab_email#12]
I am running into dependencies issues given the newer jupyterlab release. Is there a seamless way to install the app by either ignoring the dependencies or using a workaround than editing package.json and recompiling? Thanks.

**Comment by timkpaine** [comment]
@gh43r are you using jupyterlab 0.34.*? npm will let you install a tagged version, unfortunately I don't keep things well documented wrt to version compatibility.

**Comment by timkpaine** [comment]
0.1.5 is the 0.35.* version, 0.1.4 looks like the 0.34.* version, 0.1.2 is likely the 0.33.* version

**Comment by timkpaine** [comment]
@gh43r any update?
