### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

### ISSUE THREAD

**Issue by ziyi-bear** [timkpaine/jupyterlab_email#34]
Hello, I use jupyterhub to create jupyterlab, but i cant figure out how to send, It always get the error below.

![image](https://user-images.githubusercontent.com/54978757/82627915-14321580-9c1e-11ea-949a-259f4eef9b23.png)

And My config setting is 
```c.JupyterLabEmail.smtp_servers = [{'name': '聯合大學資工系郵件系統',
                                   'domain': 'gmail.com',
                                   'username': 'm0724001@gm.nuu.edu.tw',
                                   'smtp': 'smtp.gmail.com',
                                   'password': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                                   'port': 465}]
```

And the extension version is 
![image](https://user-images.githubusercontent.com/54978757/82628271-fadd9900-9c1e-11ea-8fe2-8216808506fb.png)

Many thanks

**Comment by timkpaine** [comment]
This is fixed on master

**Comment by ziyi-bear** [comment]
the version above v0.2.1 cant compatible with my current jupyterlab version

current I used those command to install 
>pip install jupyterlab_email && \
> jupyter labextension install jupyterlab_email && \
> jupyter serverextension enable --py jupyterlab_email

If i want to build from master，What command should i do after clone the repository to let it build from lastest master?

Many thanks

**Comment by timkpaine** [comment]
@ziyi-bear ill do a release soon
